name: virtuallearningapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  firebase_core: ^1.6.0
 
  
  provider: ^5.0.0
  file_picker: ^3.0.1
  http: ^0.13.3
  modal_progress_hud: ^0.1.3
  sizer: ^2.0.13
  firebase_storage: ^10.0.3
  firebase_auth: ^3.1.1
  url_launcher:
  random_string:
  shared_preferences:
  path_provider:
  better_player: ^0.0.68
  extended_image: ^4.1.0
  
  audioplayer: ^0.8.1
  audio_wave: ^0.0.3
  shimmer: ^2.0.0
  flutter_audio_recorder: ^0.5.5
  syncfusion_flutter_pdfviewer: ^19.2.60-beta
  cloud_firestore: ^2.5.2
  flutter_svg: ^0.22.0
  octo_image: ^1.0.0+1
  cached_network_image: ^3.1.0
  flutter_launcher_icons:

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icons/vlearning.png"
  image_path_ios: "assets/icons/vlearning.png"
  android: "launcher_icon"
  ios: true
  

dependency_overrides:
  process: ">=4.0.0"
  file: ^6.0.0
  
dev_dependencies:
  
 
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
